---
title: CV
format:
  quarto-cv-pdf: default
author: Lauren E. Price, M.P.P., R.T.S.B.A.
date: last-modified
phone: +1-772-485-2635
address: "Gallup StrengthsFinder: Input • Learner • Ideation • Strategic • Intellection"
email: Lauren.3.Price@gmail.com
fontsize: 11pt
#fontfamily: ebgaramond-maths # default font LaTeX package https://tug.org/FontCatalogue/about.html
#mainfont: Ubuntu # if you want to use a different locally installed font
github: pricele2 # github account
#twitter: twitter # twitter handle
web: linkedin.com 
fontawesome: yes
nocite: '@*'
# bibliography: 
#   peer: peer_bib.bib
#   other: other_bib.bib
validate-yaml: false
csl: apa-cv.csl
---

# Education

*Peabody College of Education, Vanderbilt University*, M.P.P. in Education Policy (3.92) \hfill May 2014

*College of Arts & Letters, University of Notre Dame*, B.A. Cum Laude (3.78) \hfill May 2005

# Employment

## **Texas \hfill 2014 - Present**

*[Houston Independent School District](https://www.houstonisd.org/)* 

Director, Project Management — Chief Finance and Operations Officer \hfill January 2025 - Present

Acting Director and CTM / Senior Analyst — Data Science & Analytics \hfill 2023-2024

Data Scientist and Application Developer — Research & Accountability \hfill 2021-2023

Grant Program Manager  — Research & Accountability; then School Choice \hfill 2014-2021

*[Texas Association of School Business Officials](https://www.tasbo.org/certification#module-one-section)* 

Registered Texas School Business Administrator (R.T.S.B.A.) \hfill Earned 2020; Now Maintained

## **Tennessee \hfill 2012-2014**

*Metro Nashville Public Schools.* Summer Associate for Research and Policy \hfill 2014

*Martha O'Bryan Center.* Practicum Placement, Nashville Promise Neighborhood \hfill 2013-2014

*Vanderbilt University.* Graduate Research Assistant and Summer Program Evaluation Associate \hfill 2012-2014

## **Colorado \hfill 2005 - 2011**
*Boys Hope Girls Hope of Colorado (Denver).* Development Director \hfill 2010-2011

*Community Resource Center (Denver).* Dir. for Rural Outreach; Consultant & Trainer \hfill 2008-2010

*Robert B. Sharp Company (Denver).* Capital Campaign Grant Writer & Project Manager \hfill 2007-2008

*El Pomar Foundation (Colorado Springs).* Fellow & Associate Grants Officer \hfill 2005-2007

# Recent Experiences

## **Project Management, Subject Matter Expertise, and Communicating Findings**

Negotiated project plans over needs of 5 Departments to meet CFO's goals for warehousing \hfill March 2025 - Present

Led collaboration with IT for CFO, for data pipelines to monitor actions affecting payroll \hfill January - May 2025

Identified actionable enrollment attrition trends for CAO & Schools Office. Created incentives to fight attrition, distributed campus-level data tools for retention, modeled baselines and stretch goals, calculated payouts for 30+ schools, and developed presentations to share outcomes with senior leaders. \hfill April 2024 - February 2025

Designed and implemented ML models to establish local norms and cut scores to implement CAO's policy objectives for 1,630 students entering Kindergarten in 2025 \hfill July 2024 - February 2025

Subject Matter Expert on data privacy: reviewed and revised hundreds of agreements to align over law, policy, and program needs while on HISD's Data Sharing committee \hfill November 2022 - December 2024

Authored Houston ISD’s two contract templates governing use of District data for studies or research/evaluation purposes; these Agreements now govern all studies or research in the District \hfill Summer 2024

Composed HISD's eight standard Exhibits to the National Student Data Privacy Agreement, for Information Technology and Procurement; these are now in HISD's master Terms & Conditions \hfill Spring 2024

Authored HISD's written methodology expectations for curriculum providers conducting 'impact evaluations' to meet the CAO's vision for data-driven decisions \hfill Spring 2024

Co-wrote HISD's new policies & protocols for research requests and approval processes \hfill Fall 2023

Initiated internal audit of existing contracts and data-sharing agreements; catalyzed a year-long pause on new approvals to facilitate the design, implementation of better internal controls \hfill 2022-2023

Designed and implemented randomized controlled trial (RCT) study of 115,000 students exploring marketing and decision-making for school choice \hfill 2019-2022

Project-managed evaluation of magnet programs; edited presentations to senior leaders \hfill 2019-2021

Project-managed and primary-authored 20 semi-annual reports to U.S.D.E. on team's program outcomes, financial activities, matching local funds, successes and obstacles for three discretionary grant awards:

-   Six for the 2017 Magnet School Assistance Program (MSAP, 84.165A) \hfill 2018-2021

-   Eight for the 2014 Teacher Incentive Fund (TIF4, 84.374B) \hfill 2014-2018

-   Six for the 2013 Teacher Incentive Fund (TIF3, 84.374A) \hfill 2014-2016

Wrote 4 major program evaluation reports, two in collaboration with external technical assistance: causal inference analysis for improving STAAR scores, and cohort analysis for STEM teacher attrition \hfill 2014-2018

<!-- Designed survey for CAO and presented actionable findings on staff perceptions of performance based compensation strategies; implemented population-group statistical weights for findings \hfill 2015-2016 -->

## **Leading Recent Partnerships with External Entities**

[Innovation Science for Education Analytics (ISEA)](https://www.amplifylearn.ai/isea/): Selected for competitive six-month data science training program funded by the Institute of Education Sciences at the University of Washington \hfill January - June 2025

[Information Task Force, Texas Education Agency (TEA)](https://www.texasstudentdatasystem.org/TSDS/About/Data_Governance/User_Involvement_and_Data_Governance): Appointed and active member of statewide advisory committee, setting data policy for Texas Student Data System \hfill August 2023 - January 2025

[Riverside Insights](https://riversideinsights.com/cognitive_abilities_test): Primary investigator for experimental use of CogAT assessment to identify early elementary students eligible for Gifted and Talented services \hfill June - December 2024

<!-- [University of Houston](https://uh.edu/education/aces/): Technical expert for agreements over data supporting tutoring collaborative \hfill 2024 -->

[Population And Survey Analytics (PASA)](https://pasatx.com/): District project manager for major contract covering ten-year demographic forecasts, incorporating geocoded student addresses, Census, GIS, and HCAD datasets \hfill 2022-2024

[Contigo Ed](https://contigoed.org/our-work): District project manager for data audit funded by the Houston Endowment, compiling a decade of student outcomes and program data related to College, Career, and Military Readiness (CCMR) \hfill 2023-2024

[RAND Corporation](https://doi.org/10.26300/e3bq-7g59): Primary analyst, liaison, and HISD data manager for randomized controlled trial (RCT) funded by the Institute for Education Sciences, evaluating the efficacy of Zearn curriculum for improving student math outcomes in grades 3 to 5; Authored 2 years of technical documentation and coached up junior analyst to ensure Y2 deliverables met my standards from Y1 \hfill 2022-2024

[Good Reason Houston](https://goodreasonhouston.org/about-us/) & [Kitamba/MGT](https://www.linkedin.com/company/kitamba-management-inc): Senior analyst for leadership transition planning; subject matter expert consulted for input across multiple areas \hfill 2023-2024

[Houston Food Bank](https://www.houstonfoodbank.org/our-programs/): Wrangled messy raw files from Wraparound, HFB, and PEIMS to assess impact; interpreted metadata and findings and translated results into actionable insights for district and NGO leaders \hfill 2022 - 2023 

[Panorama Education](https://www.panoramaed.com/about): Analyst for rostering student perception surveys for teacher evaluation \hfill Spring 2022

[Houston Education Research Consortium (HERC) at Kinder Institute, Rice University](https://kinder.rice.edu/centers/houston-education-research-consortium) Thought partner and collaborator providing clean data and technical expertise for high-stakes projects covering school choice, post-secondary readiness, equity in program access, and student mobility \hfill 2019-2022

[NASA Johnson Space Center](https://www.nasa.gov/learning-resources/for-educators/) Project manager handling contracts, POs, schedules, digital credentials, and policy documents to connect teachers with NASA's K-8 curriculum and job-embedded coaching \hfill 2018-2021

[Education Analytics](https://www.edanalytics.org/who-we-are): Designed a collaborative analysis on efficacy of specific compensation strategies \hfill 2018

## **Analysis, Data Management, and Modeling**
Modeled cost estimates for CFO over mutually exclusive operational plans \hfill February - April 2025

Wrote complex ETL pipelines in SQL and R for staff rosters, student enrollment, course assignments, and geospatial data: collaborated with Chief of Staff and CAO to flag and remedy under-staffing or overcrowding at 200 schools \hfill August - September 2024 

Subject matter expert on Houston ISD pre-K, transforming the District discourse about current and future needs. Designed and implemented deep analysis to shape expansion strategy: \hfill January 2023 - December 2024

- Built initial models and business rules for [Pre-Kindergarten Seats Available](https://houstonisd-gis-houstonisd.hub.arcgis.com/apps/26799e8d624c4bb6b30d6ac2320b840f/explore) resource, led improvements for SY2425, and coached junior analysts on workflows and *ad hoc* requests \hfill September 2023 - December 2024

- Prioritized bond investments over supply/demand metrics and forecasts \hfill March - June 2024

- Used open-source Census tools to prioritize district outreach in neighborhoods with income and language demographics likely to qualify for state-funded pre-K programming  \hfill April 2024

- Built multivariate scoring model for Chief Academics Officer to understand pre-K supply/demand at 160+ campuses; oversaw junior analyst’s downstream deliverables \hfill March 2024

- Determined feasibility of expansion at +20 schools: Led team of analysts and program specialists incorporating floorplans, Google Earth, and in-person walkthroughs \hfill March 2024

- Implemented reframing of district policy to *supply* (staffed pre-K seats) and *demand* (kids) \hfill February 2023
  
Identified risks and errors, codified sources & business rules, and established daily messaging to campus leaders for the timely resolution of anomalies on student course assignments and campus master schedules; ensured compliance with state and local regulations for testing and data collections. \hfill July - October 2024

Improved user uptake and increased transparency by overhauling the annual [Campus Demographic Report](https://www.houstonisd.org/Page/202084) data model and its visualization; handed off my reproducible workflows to junior analysts \hfill February 2022 - May 2024

Senior analyst then project manager for [SchoolFinder](https://schoolfinder.houstonisd.org/Dashboard/module-resource/school-finder): scripted the reshaping of raw files into complex deliverables, negotiated with vendor, and onboarded team to my reproducible scripts \hfill October 2021 - March 2024

Scripted machine learning models to sort 250+ schools into *k*-means clusters across similar (1) building conditions, (2) academic achievement, and (3) financial risk exposure to low enrollment. \hfill August 2022

Ideated analysis and found 500 additional students likely experiencing homelessness: using home addresses, Texas public data, and Change of Address files from U.S.P.S. and LexisNexis \hfill December 2021


## Technical Proficiencies

|               |        |     |             |          |
|---------------|--------|-----|-------------|----------|
| R/Posit       | 5 of 5 |     | Stata       | 4 of 5   |
| MS Excel      | 5 of 5 |     | Rmd/Quarto  | 3.5 of 5 |
| MS SharePoint | 5 of 5 |     | LaTeX       | 3 of 5   |
| MS Access     | 4 of 5 |     | Python      | 2 of 5   |


# Awards & Invitations

Oct 2024. *EDAD 688 Education Policy Series*, Guest Speaker \hfill Texas A&M

Apr 2023. *IS595 Competitive Intelligence & Knowledge Management*, Guest Speaker \hfill Univ. of Illinois

Jul 2022. *Diversity Scholarship*, Conference and Workshop \hfill [posit::conf](https://posit.co/conference/faq/), formerly RStudio

Oct 2021. *Featured Publication*, TIF Evaluations 1, 2 & 3 \hfill [ArnieDocs](https://www.arniedocs.info/)

Oct 2021. *Making Performance Pay Pay Off*, Conference Presentation \hfill Council of Great City Schools

Nov 2018. *SOCI 437/537 Sociology of Education*, Guest Speaker \hfill Rice University

May 2015. *Parents, Teachers, and Title I*, Conference Presentation \hfill CRSEA 9th Annual Conference

# Selected Publications

Pane, J., Doss, C., Todd, I., & Seaman, D. (2025). Efficacy of Zearn Math over two years in grades 3 to 5: An experiment in Texas. (EdWorkingPaper: 25-1211). Retrieved from Annenberg Institute at Brown University: https://doi.org/10.26300/e3bq-7g59

Price, L., & Islam, F. (2025, February). Technical Documentation: Local Norms & GT Matrix Scores for Students Entering Kindergarten in SY25-26. Houston ISD: Data Science.

Price, L., & Cortez, J. (2024, September 30). Technical Documentation for Efficacy of Zearn Math, IES Award [R305A230170](https://ies.ed.gov/funding/grantsearch/details.asp?ID=5835). Houston ISD: Data Science.

Price, L., Lasode, M., & Powers, K. (2023, December 13). Memorandum To Chief Financial Officer: FY25 Forecasting Models for Student ADA. Houston ISD: Internal Publication.

Lasode, M., Price, L., Abdoli, M., & Hovey, I. (2022, July 7). [2021-2022 Campus Demographic Report](https://www.houstonisd.org/site/handlers/filedownload.ashx?moduleinstanceid=392028&dataid=424429&FileName=Campus%20Demographic%20Report%202021-2022.pdf). Houston ISD: Research and Accountability.

Price, L., & Scuello, M. (2022, May). Evidence of Promise from the Magnet Schools Assistance Program: Recruiting Students to HISD’s Secondary STEM Magnet Schools. Houston ISD: Internal Publication.

Price, L. (2022, April 1). Public Comment ID 6op2zxpf4i on [WWC Version 5.0](https://ies.ed.gov/ncee/wwc/)

Price, L., & Matney, A. (2021, December 14). Memorandum to Executive Officer, Student Support: Additional Students Identified as Eligible For Services. Houston ISD: Internal Publication.

Aulicino, C., Rinehart, C., & Price, L. (2021, October). Secondary STEM Magnet Programs Study: Year 2. Metis Associates. Internal Publication.

Aulicino, C., Rinehart, C., & Price, Lauren. (2020, September). STEM Magnet Program Study: Year 1. Metis Associates. Internal Publication.

Price, L., Christian, M., & Stevens, C. (2018a). A Matched-Comparison Analysis of Math and Science STAAR Scores: Teacher Incentive Fund STEM Grant in Houston ISD. Houston ISD: Research And Accountability. [ERIC Number ED603680](https://eric.ed.gov/).

Price, L., Cramer, E., Milanowski, A., Mader, J., Robertson, D., & Stevens, C. (2018b). A Human Capital Approach to Improving STEM Education: Teacher Incentive Fund STEM Grant in Houston ISD. Houston ISD: Research and Accountability. [ERIC Number ED603681](https://eric.ed.gov/).

Price, L., Provencher, S., & Stevens, C. (2018c). A Descriptive Overview: Teacher Incentive Fund STEM Grant in Houston ISD. Houston ISD: Research and Accountability. [ERIC Number ED603678](https://eric.ed.gov/).

Price, L., & Stevens, C. (2017). Teacher Incentive Fund, Cohort 3—Looking Back, Around, And Ahead: HISD’s Viewfinder For Teacher And Leader Effectiveness. Houston ISD: Research and Accountability.

Price, L., Jordan, S., & Stevens, C. (2016, January). Preferences and Perspectives on Teacher Compensation, 2014-2015. Houston ISD: Internal Publication.

# References

[Jorge Martinez](mailto:jxmhtx@icloud.com). Director of Data Strategy \hfill BakerRipley

[Isabel Hovey](mailto:isabel.hovey@gmail.com). Director of Accountability, Research, & Compliance \hfill Region IV ESC

[Tanya Pridgeon](mailto:tpridgeo@houstonisd.org). Senior Manager, IT Strategic Planning \hfill Houston ISD

[Dr. Allison Matney](mailto:aematney@gmail.com). Sr. Consultant, TX Center for School Accountability \hfill STRIVE Public Policy Resources

[Dr. Erin Baumgartner](mailto:erinbaumgartner@rice.edu). Director, Houston Education Research Consortium \hfill Kinder Institute, Rice University

[Marco Heredia](mailto:marco@contigoed.org). Partner, Analytics \hfill Contigo Ed

# Skills & Competencies

*Ad Hoc* Analysis • *Ad Hoc* Reporting • Analytical Skills • Annual Budgeting • Budgeting • Business Analysis • Business Insights • Business Process • Children’s Online Privacy Protection Act "COPPA" at 16 CFR § 312 • Client Relations • Community Impact • Compilation • Contract Negotiation • Contract Writing • Creative Problem Solving • Creative Strategy • Data Analytics • Data Governance • Data Integrity • Data Interpretation • Data Management • Data Manipulation • Data Modeling • Data Retention • Data Privacy • Data Science • Data Strategies • Data Systems • Database Administration • Database Systems • Databases • Donor Relations • Econometrics • Education Department General Administrative Regulations "EDGAR" at 2 CFR and 34 CFR • Extract, Transform, Load (ETL) • Family Educational Rights and Privacy Act "FERPA" at 34 CFR § 99 • Key Performance Indicators • KPI Reporting • Large-scale Data Analysis • Leadership • Legal Requirements • Logic Models • Machine Learning • Metadata • Microsoft Excel • Microsoft Office • Policy Analysis • Policy Writing • Presentations • Primary Research • Privacy Regulations • Problem Solving • Program Assessment • Program Evaluation • Project Management • Quality Assurance • R •  RStudio/Posit • Relational Databases • Reporting Requirements • Spreadsheets • Stata • Statistical Analysis • Statistics • Statutes • Team Management • Texas Education Code "TEC" • Tenacious Work Ethic • Texas Government Code "TGC" • Vendor Relations • Written Communication
