---
title: CL
format:
  quarto-cv-pdf: default
filters:
- style-text # https://github.com/leovan/quarto-style-text#readme
author: Lauren E. Price, M.P.P., R.T.S.B.A.
date: last-modified
phone: +1-772-485-2635
address: "Gallup StrengthsFinder: Input • Learner • Ideation • Strategic • Intellection"
email: Lauren.3.Price@gmail.com
fontsize: 11pt
#fontfamily: ebgaramond-maths # default font LaTeX package https://tug.org/FontCatalogue/about.html
github: pricele2 # URL linked in quarto-cv.tex
web: linkedin.com # URL linked in quarto-cv.tex 
fontawesome: yes
nocite: '@*'
# bibliography: 
  # peer: peer_bib.bib
  # other: other_bib.bib
validate-yaml: false
csl: apa-cv.csl

editor_options:
  markdown:
    wrap: 80
---
```{r}
#| include: false
color <- '#ffffff' 
opacity <- 0.8
font <- 'Times New Roman'
font_size <- 2
```
::: {.style-text color="`{r} color`"}
<!-- Lorem ipsum sit dolor amet -->
:::
\vspace{8 mm}

\apstylekinda\today

\vspace{2 mm}

\begin{tabular}{ p{10cm} }
Tom Lynch, Chief Information Officer \\
Bureau of Technology (BOT), Cook County \\ 
161 North Clark, Suite 500 \\
Chicago, Illinois \\
\end{tabular}

Dear Mr. Lynch:  

I am pleased to submit my application for Financial Affairs and Grants Management Director to support the Bureau of Technology team within the Offices Under the President, Cook County (Req. 00137951). My career is built on providing strategic leadership, robust fiscal oversight, and successful grants management for local government and nonprofit organizations. 
From my 11 years with Houston Independent School District, I bring seven years of federal grant management and financial leadership, including six years of supervisory experience and four years of mission-critical data responsibilities. Furthermore, I hold a master’s degree in public policy (Vanderbilt, 2014) and the highest credential from the Texas Association of School Business Officials (RTSBA, 2020) — providing me with a thorough knowledge of the principles, practices, and terminology of general and governmental accounting.

In 2025, I’ve provided strategic leadership, thought partnership, and project management for the senior-most leaders over $2.1 billion in annual operations. And now I’m excited to continue my journey by contributing to a government agency with a broader vision of how a public agency can support its constituents. There are five specific aspects of my resume that make me a terrific fit for this leadership role: 

* __Policy & Enforcement.__ As I demonstrated in my successful leadership of three federal discretionary grants (over $60m), I have a proven ability to develop, recommend, and implement financial and grant program policies and procedures to ensure strong fiscal accountability and effective control systems.

* __Budgeting & Analysis.__ A significant part of my professional experience involves the coordination of semi-annual budget formulation, including analysis and ranking of departmental budget requests (including staffing needs), and directly preparing semi-annual and special financial statements.

* __Grants & Compliance.__ I have deep experience in overseeing overall grant efforts, providing leadership for programs funded by federal (2014-2021) and state/private grants (2005-2011), and ensuring strict compliance and reporting requirements are met by all program staff. 
* __Technology & Problem Solving.__ I am an experienced and creative analyst, a power user of ERP software applications to access and manipulate financial and operations data, and to solve complex problems with a long-term impact on the organization. E.g., in 2015-2018 I doubled grant program outcomes thanks to schedule changes suggested by my analysis.

* __Liaison/Consultation.__  My interpersonal skills as a colleague and a leader allow me to effectively serve as a primary liaison for senior leadership regarding financial matters impacting bureau/department programs, while continually consulting with internal stakeholders to evaluate issues and identify opportunities for efficiencies. 

In conclusion, I am eager to apply my expertise to implement a broader vision for the role of government in public life, ensuring the strategic use of technology-related assets and funds. I am prepared to oversee all financial control and grant management functions for the BOT, and work with senior leaders across multiple lanes to lead the analysis, formulation, presentation, and reporting of the BOT annual budget. I am confident that my experience and dedication to public service align neatly with the requirements of the Director position, and I welcome the opportunity to discuss my qualifications further. 

Thank you for your time and consideration.  

\vspace{4 mm}
Regards,

Lauren E. Price