---
title: CL
format:
  quarto-cv-pdf: default
filters:
- style-text # https://github.com/leovan/quarto-style-text#readme
author: Lauren E. Price, M.P.P., R.T.S.B.A.
date: last-modified
phone: +1-772-485-2635
address: "Gallup StrengthsFinder: Input • Learner • Ideation • Strategic • Intellection"
email: Lauren.3.Price@gmail.com
fontsize: 11pt
#fontfamily: ebgaramond-maths # default font LaTeX package https://tug.org/FontCatalogue/about.html
github: pricele2 # URL linked in quarto-cv.tex
web: linkedin.com # URL linked in quarto-cv.tex 
fontawesome: yes
nocite: '@*'
# bibliography: 
  # peer: peer_bib.bib
  # other: other_bib.bib
validate-yaml: false
csl: apa-cv.csl

editor_options:
  markdown:
    wrap: 80
---
```{r}
#| include: false
color <- '#ffffff' 
opacity <- 0.8
font <- 'Times New Roman'
font_size <- 2
```
::: {.style-text color="`{r} color`"}
<!-- P.S. My bibliograpy for the project will be sent if you interview me -->
:::
\vspace{4 mm}

\apstylekinda\today

\vspace{2 mm}

\begin{tabular}{ p{10cm} }
Reverend Dr. Frank Clark Spencer, President \\
The Board of Pensions of the Presbyterian Church (U.S.A.) \\
2000 Market Street \\
Philadelphia, Pennsylvania \\
\end{tabular}

Dear Rev. Dr. Spencer:

I am pleased to submit my application for the Director of Enterprise Reporting & Analytics position at the Board of Pensions of the PC(USA), as advertised on LinkedIn. I am deeply drawn to the opportunity to leverage my strategic data leadership skills in service of the Board’s mission to provide security to those who have faithfully served the Church. My extensive experience building and scaling robust reporting tools and data governance deliverables aligns with your need for accurate, timely, and actionable insights. I possess the skills and values the Board requires to establish your reporting standards, business intelligence protocols, and enterprise analytics roadmap. 

On the people side of the work, I am an experienced leader with six years of mentoring, managing, and developing technical analysts and customer-facing program staff. I set high expectations and clear parameters, establish collaborative practices and team norms, and then coach up where needed for consistent results for our customer-stakeholders. I excel in fostering a high-performing, mission-focused culture, prioritizing my team members’ curiosity and continuous professional growth at all career stages. I believe in empowering my team members to become strategic advisors to the leaders over each domain — and coaching them to translate their knowledge into key decision-points. I build trust with my team members by getting into the weeds as needed,to demonstrate my own expertise. My analytics skills began my master's program (2012-2014), where  I excelled in the quant-heavy coursework. These skills deepened over 11 years of data science and finance analytics work in local government. 

Crucially, I have experience in defining business requirements and documenting KPI calculations for data pipelines, warehousing, and ERP integrations concerning Finance, Payroll, and Benefits. I have successfully lead complex short- and long-term analytic projects: from design and modeling through development, production, publication, and cyclical revisions, while ensuring technical rigor, precise parameters, and ethical handling of data at every step. I excel at partnering with leaders across functional areas to ask the right questions, model and interpret the right data, and deliver meaningful insights. I have a track record of developing predictive and trend-based analytics to support executive decision-making. Recently, my analytics guided $200 million of planned capital investment to expand early childhood education over ten years. I am comfortable serving as a trusted advisor to executives and Board members on simple performance trends and complex analytic models alike. My familiarity with enterprise platforms and operational protocols across the Board’s major functional areas will ensure I can immediately begin to optimizing and integrate your existing technology stack without a steep learning curve. 

This role represents a unique opportunity to combine my dedication to mission-driven work, deeply rooted in the justice values of my theology degree, with my professional expertise in sophisticated data leadership. Thank you for reviewing my comprehensive qualifications for this leadership role. I look forward to discussing in more detail how I can immediately impact the Board’s success in serving your 65,000 members. 

Regards,

Lauren E. Price