---
title: CV
format:
  quarto-cv-pdf: default
author: Lauren E. Price, M.P.P., R.T.S.B.A.
date: last-modified
phone: +1-772-485-2635
address: "Gallup StrengthsFinder: Input • Learner • Ideation • Strategic • Intellection"
email: Lauren.3.Price@gmail.com
fontsize: 11pt
#fontfamily: ebgaramond-maths # default font LaTeX package https://tug.org/FontCatalogue/about.html
#mainfont: Ubuntu # if you want to use a different locally installed font
github: pricele2 # github account
#twitter: twitter # twitter handle
web: linkedin.com 
fontawesome: yes
nocite: '@*'
# bibliography: 
#   peer: peer_bib.bib
#   other: other_bib.bib
validate-yaml: false
csl: apa-cv.csl
---

# Education & Credentials
*University of Washington*,
NCES Fellowship in [Innovation Science for Education Analytics (ISEA)](https://www.amplifylearn.ai/isea/) \hfill June 2025

*TX Assoc. of School Business Officials*, Registered Texas School Business Administrator (R.T.S.B.A.) \hfill Sept. 2020

*Vanderbilt University*, Master's of Public Policy in Education Policy & Leadership (3.92) \hfill May 2014

<!-- - Thesis: Parents and Teachers in Title I Schools: A Critical Race Theory Analysis of Parent Engagement -->

*University of Notre Dame*, Bachelor of Arts *cum laude* (3.78) \hfill May 2005

# Employment Overview

## **Texas \hfill 2014 - 2025**

*Houston Independent School District (HISD)* 

Director, Finance Project Management \hfill Jan. - Sep. 2025

Deputy Director & Senior Analyst, Data Science & Analytics \hfill Oct. 2021 - Dec. 2024

Grant Manager & Program Analyst, Special Revenue \hfill Aug. 2014 - Oct. 2021

## **Tennessee \hfill 2012-2014**

*Metro Nashville Public Schools.* Summer Associate for Research and Policy \hfill 2014

<!-- *Martha O'Bryan Center.* Practicum Intern, Nashville Promise Neighborhood \hfill 2013-2014 -->

*Vanderbilt University.* Graduate Research Assistant & Summer Program Evaluation Associate \hfill 2012-2014

## **Colorado \hfill 2005 - 2011**
*Boys Hope Girls Hope of Colorado (Denver).* Development Director \hfill 2010-2011

*Community Resource Center (Denver).* Program Associate & Project Coordinator \hfill 2008-2010

*Robert B. Sharp Company (Denver).* Project Coordinator, Feasibility Studies \& Capital Campaigns \hfill 2007-2008

*El Pomar Foundation (Co. Springs).* Program Coordinator & Associate Grants Officer \hfill 2005-2007

# Experiences

## **Data Strategy & Product Ownership**

Led organization's negotiations on strategy and data-use agreements with external NGOs like [TFA](https://en.wikipedia.org/wiki/Teach_For_America) and [United Way](https://unitedwayhouston.org/what-we-do/youth-success/united-way-bright-beginnings/); subject-matter expert on the availability and best use of student data per law and policy. \hfill 2021-2025  

**Data Product "Enrollment Incentives" —** Escalated actionable enrollment trends for C-suite leaders: Modeled cash incentives to counteract attrition, distributed campus-level data tools to augment student retention, calculated baselines and stretch goals, calculated payouts for 30+ schools, and wrote presentations to communicate outcomes with senior leaders. \hfill Apr. 2024 - Feb. 2025

Set data policy and reporting strategy for > 1,000 districts: appointed member of statewide advisory committee for data governance, the [Information Task Force, Texas Education Agency (TEA)](https://www.texasstudentdatasystem.org/TSDS/About/Data_Governance/User_Involvement_and_Data_Governance). \hfill Aug. 2023 - Jan. 2025  

**Data Product "Capping Tool" —** Drove daily staff decisions at 200 schools: Wrote and modeled ETL pipelines across SQL, R, Python, and PowerBI to clean, join, publish findings from data on staff rosters/titles, student characteristics, course assignments, student-teacher linkage, and geospatial data. \hfill Jan. 2022 - Oct. 2024

**Data Product "Pre-K Scheduling" —** Established seamless cross-platform daily workflow for same-day resolution of errors in student course assignments and master schedules: flagged errors, standardized sources & business rules, and pushed daily actionable messaging to nearly 200 school leaders.  \hfill Jul. - Oct. 2024

**Data Product "GT Testing Requests" —** Created Qualtrics instruments & workflows to intake, de-duplicate, and conditionally route requests to test > 37,000 students at > 160 schools. \hfill Aug. 2023 - Oct. 2024 

Modernized organization's data sharing strategy by composing District's eight standard Exhibits to National Student Data Privacy Agreement, which are now in master Terms & Conditions for all Procurement. \hfill Spring 2024  

Solved a material data governance weakness by authoring District's contract templates for external entities using data for studies/audit/evaluation, strengthening protections for student privacy. \hfill Jan. - Oct. 2024  

Authored methodology constraints & product expectations, implemented equitable data sharing for curriculum providers conducting 'impact evaluations' to meet C-suite's vision for data-driven decisions. \hfill Spring 2024  

Active member of district Data Sharing Committee: Reviewed & revised hundreds of agreements to align over law, policy, and strategy, program needs in bi-weekly working sessions. \hfill Nov. 2022 - Dec. 2024  

Co-wrote District's new policies & protocols for research requests and approval workflows \hfill Fall 2023  

<!-- Initiated internal audit of current contracts and data-sharing agreements; Findings catalyzed a year-long pause on new work to facilitate the design, implementation of better internal controls \hfill 2022-2023   -->

## **Advanced Analytics Delivery**

Modeled iterations of capital project cost estimates for CFO over mutually exclusive plans. \hfill Spring 2025  

Primary Investigator (PI) for experimental use of [CogAT](https://riversideinsights.com/cognitive_abilities_test) assessment and subsequent Monte Carlo modeling of local norms from Riverside Insights; implemented cut scores for 1,630 students. \hfill Jun. - Dec. 2024

Data manager for external program audit by [Contigo Ed](https://contigoed.org/our-work), compiling 10+ years of student outcome, achievement & programming metrics related to college, career, and military readiness. \hfill 2023-2024

District data manager and liaison for randomized controlled trial (RCT) by RAND Corporation [funded by Institute for Education Sciences](https://ies.ed.gov/use-work/awards/efficacy-zearn-math), evaluating the efficacy of Zearn curriculum for student math outcomes; Authored 2 years of technical documentation and coached up junior analyst for future deliverables. \hfill 2022-2024

Data manager for contract with [Population And Survey Analytics](https://pasatx.com/), developing ten-year demographic forecasts using student characteristics, geocoded addresses, Census, shapefiles, and county appraiser data. \hfill 2022-2024

Overhauled data model and visualization for annual [Campus Demographic Report](https://tx01001591.schoolwires.net/site/handlers/filedownload.ashx?moduleinstanceid=392028&dataid=424429&FileName=Campus%20Demographic%20Report%202021-2022.pdf) dashboard, improving user uptake and increasing transparency; onboarded jr. analysts to reproducible workflows for future years. \hfill 2022-2024

Wrangled messy raw files from internal, external, and state data to assess collaboration with [Houston Food Bank](https://www.houstonfoodbank.org/our-programs/); interpreted metadata/findings and presented actionable insights for District and NGO leaders. \hfill 2022 - 2023

Designed and scripted ML models to organize 250+ schools into *k*-means clusters across (1) building conditions, (2) academic achievement, and (3) financial risk exposure to low enrollment. \hfill Aug. 2022

Standardized and programmed complex student-teacher rosters for high-stakes survey by [Panorama](https://panoramaed.com/about). \hfill 2022

Senior analyst and data manager for editions of [SchoolFinder](https://schoolfinder.houstonisd.org/Dashboard/module-resource/school-finder): reshaped messy disparate raw files into complex deliverables, negotiated with vendor, and onboarded junior staff to my github/Qualtrics workflow. \hfill 2021-2024

Designed and implemented analysis of public, District, and proprietary (Change of Address) data sources to identify 500 additional students likely experiencing homelessness. \hfill Dec. 2021

Primary Investigator (PI) for randomized controlled trial (RCT) study of 115,000 enrolled students over two years, exploring marketing, behavior nudges, and family decision-making for school choice. \hfill 2019-2022

Thought partner and active collaborator with [Houston Education Research Consortium (HERC) at Kinder Institute at Rice University](https://kinder.rice.edu/centers/houston-education-research-consortium), providing clean data and technical expertise for quantitative projects covering school choice, post-secondary readiness, equity in program access, and student mobility. \hfill 2019-2022

Ideated and project-managed evaluation of magnet programs; co-wrote presentations to senior leaders. \hfill 2019-2021

Designed collaboration on causal inferences with [Education Analytics](https://www.edanalytics.org/who-we-are ) on performance pay strategies. \hfill 2018

Designed and administered survey to 11,000 teachers; presented actionable findings on staff perceptions of performance based compensation strategies; implemented population-group statistical weights for findings. \hfill 2015-2018

Designed continuous improvement strategies for human capital outcomes within bonus-driven program: Schools doubled teacher retention by implementing my recommendations. \hfill 2015-2018

Queried, organized, cleaned, and analyzed 70+ complex datasets capturing 8 years of District-wide indicators over school choice applications, lottery outcomes, student achievement, and teacher labor market choices. \hfill 2014-2021

Authored 20 semi-annual program reports to USDE, including budget-to-actual narratives, SWOT analyses of implementation, and longitudinal metrics for student achievement and human capital. \hfill 2014-2021

Wrote 4 major program evaluation reports, two in collaboration with external technical assistance: causal inference analysis for improving STAAR scores, and cohort analysis for STEM teacher attrition. \hfill 2014-2018

## **Team Leadership & Stakeholder Management**

Defined and executed agency-wide training and compliance strategy, by overhauling 500+ pages of internal controls (Finance Manual) to reframe technical and regulatory content for the average campus-based clerk. \hfill Summer 2025  

Led special projects and managed projects for cross-functional initiatives owned by CFO and Senior Exec. Directors of Payroll, Controller, Treasury, Procurement, and Warehouse. \hfill 2025  

Drove data-driven adjustments to improve timeliness in accounts payable and payroll actions. \hfill 2025  

Liaised with Council for Great City Schools (CGCS) leadership, ensuring reliable reproducible results for local and national KPIs across 16+ areas of operation. \hfill 2023-2025  

Senior analyst for TEA takeover transition planning by [Good Reason Houston](https://goodreasonhouston.org/about-us/) & [Kitamba/MGT](https://www.linkedin.com/company/kitamba-management-inc); subject matter expert consulted for expertise across HR, finance, planning, and accountability domains. \hfill 2023-2024  

Led team of five analysts to write and implement reproducible scripts to pull, clean, process/ETL, reshape, join, analyze, and deliver daily work product to C-Suite leaders. \hfill July 2023 - Dec. 2024  

Conducted code reviews, QA tests, and coaching for junior and peer analysts’ work product. \hfill 2021-2024  

Project manager for seven-figure agreement with [NASA Johnson Space Center](https://www.nasa.gov/learning-resources-for-educators/); handled contracts, POs, work schedules and credentials: connected teachers with STEM curriculum and job-embedded coaching. \hfill 2018-2021  

Negotiated scopes of work, monitored work for hire, and resolved disputes with vendors, universities, technical assistance providers, nonprofit/research partners. \hfill 2014-2024  

Monthly review and reconciliation of financials to ensure alignment with USDE standards (EDGAR), as well as GAAP, GASB, and state regulations (FASRG) for government accounting. \hfill 2014-2021  

Led day-to-day financial management, planning, evaluation, and implementation for $60.3 million in federal & matching expenditures under three USDE discretionary grants (84.165A, 84.374B, and 84.374A). \hfill 2014-2021  

Ensured on-time and in-scope spending: e.g., closed 84.374B with < \$10.00 unspent. \hfill 2014-2021

## **Pre-Kinder Center of Excellence**

Subject matter expert and team lead for entire workstream related to pre-Kindergarten goals and metrics, including current/future needs. Designed and implemented deep analysis to shape expansion strategy, e.g.: \hfill Dec. 2022 - Feb. 2025  

* Built initial models and business rules for ArcGIS map tool showing Seats Available, led model improvement for SY2425, and coached jr. analysts to reproduce workflows and *ad hoc* requests \hfill Sep. 2023 - Dec. 2024  
    
* Allocated $200M of bond investments over supply/demand and forecast metrics \hfill Mar. - Jun. 2024

* Determined feasibility of expansion at +20 schools: Led team of analysts and program specialists incorporating floorplans, Google Earth, and in-person walkthroughs \hfill Mar. 2024  

* Built multivariate scoring model for Chief Academics Officer to understand pre-K supply/demand at 160+ campuses; oversaw junior analyst’s downstream deliverables \hfill Mar. 2024  

* Implemented reframing of district policy to supply (staffed pre-K seats) and demand (kids) \hfill Feb. 2023  

* Designed and modeled cohort attrition between PK4 and Kinder, advising leadership and shaping recruitment strategy around patterns of weak retention \hfill Dec. 2022 - Dec. 2024 

# Technical Proficiencies
\begin{tabular}{ p{4cm}  p{1.5cm}  p{4cm}  p{1.5cm}  }
R                   & 5 of 5  & Git, GitHub & 4 of 5 \\
Excel, PowerQuery   & 5 of 5  & Stata       & 4 of 5 \\
PowerSchool SIS     & 5 of 5  & Rmd, Quarto, LaTeX  & 3 of 5 \\ 
SharePoint Admin    & 5 of 5  & PowerBI, Tableau & 3 of 5  \\ 
Qualtrics PowerUser & 4 of 5  & Python      & 2 of 5 \\ 
PeopleSoft, SAP ERP & 4 of 5 & SQL      & 2 of 5 \\
\end{tabular}

# Invitations & Awards

Nov 2025. *IS594 Change Catalyst*, Guest Speaker \hfill Univ. of Illinois School of Information Sciences

Oct 2024. *EDAD 688 Education Policy Series*, Guest Speaker \hfill Texas A&M College of Education

Apr 2023. *IS595 Competitive Intelligence & Knowledge Management*, Guest Speaker \hfill Univ. of Illinois

Jul 2022. *Diversity Scholarship*, Conference and Workshop \hfill [posit::conf](https://posit.co/conference/faq/), formerly RStudio

Oct 2021. *Featured Publication*, Teacher Incentive Fund (TIF) Evaluations \hfill [ArnieDocs](https://www.arniedocs.info/)

Oct 2021. "Making Performance Pay Pay Off," Conference Presentation \hfill Council of Great City Schools

Nov 2018. *SOCI 437/537 Sociology of Education*, Guest Speaker \hfill Rice University

May 2015. "Parents, Teachers, and Title I," Conference Presentation \hfill [CRSEA](https://crsea.org/crt-101/) 9th Annual Conference

# Selected Publications

Pane, J., Doss, C., Todd, I., & Seaman, D. (2025). Efficacy of Zearn Math over two years in grades 3 to 5: An experiment in Texas. (EdWorkingPaper: 25-1211). Retrieved from Annenberg Institute at Brown University: [https://doi.org/10.26300/e3bq-7g59](https://doi.org/10.26300/e3bq-7g59)

Price, L., & Islam, F. (2025, February). [Technical Documentation](https://www.linkedin.com/in/lauren-e-price-mpp/overlay/1741980965844/single-media-viewer?type=DOCUMENT&profileId=ACoAAADz6gABmAId2NX7YwelXulJgIDVVKZ5mts&lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base%3BGrQgHVtmTRmsyGnRySj2Dg%3D%3D): Local Norms & GT Matrix Scores for Students Entering Kindergarten in SY25-26. HISD: Data Science & Analytics.

Price, L., & Cortez, J. (2024, September 30). Technical Documentation for Efficacy of Zearn Math, IES Award [R305A230170](https://ies.ed.gov/funding/grantsearch/details.asp?ID=5835). HISD: Data Science & Analytics.

Price, L., Lasode, M., & Powers, K. (2023, December 13). Memorandum To Chief Financial Officer: FY25 Forecasting Models for Student Average Daily Attendance. HISD: Internal Memo.

Lasode, M., Price, L., Abdoli, M., & Hovey, I. (2022, July 7). [2021-2022 Campus Demographic Report](https://tx01001591.schoolwires.net/site/handlers/filedownload.ashx?moduleinstanceid=392028&dataid=424429&FileName=Campus%20Demographic%20Report%202021-2022.pdf). HISD: Research and Accountability.

Price, L., & Scuello, M. (2022, May). Evidence of Promise from the Magnet Schools Assistance Program: Recruiting Students to HISD’s Secondary STEM Magnet Schools. HISD: Internal Publication.

Price, L., & Matney, A. (2021, December 14). Memorandum to Executive Officer, Student Support: Additional Students Identified as Eligible Under McKinney-Vento. HISD: Internal Memo.

Aulicino, C., Rinehart, C., & Price, L. (2021, October). Secondary STEM Magnet Programs Study: Year 2. Metis Associates: Internal Publication for HISD.

Aulicino, C., Rinehart, C., & Price, Lauren. (2020, September). STEM Magnet Program Study: Year 1. Metis Associates: Internal Publication for HISD.

Price, L., Christian, M., & Stevens, C. (2018a). A Matched-Comparison Analysis of Math and Science STAAR Scores: Teacher Incentive Fund STEM Grant in Houston ISD. HISD: Research And Accountability. [ERIC Number ED603680](https://eric.ed.gov/).

Price, L., Cramer, E., Milanowski, A., Mader, J., Robertson, D., & Stevens, C. (2018b). A Human Capital Approach to Improving STEM Education: Teacher Incentive Fund STEM Grant in Houston ISD. HISD: Research and Accountability. [ERIC Number ED603681](https://eric.ed.gov/).

Price, L., Provencher, S., & Stevens, C. (2018c). A Descriptive Overview: Teacher Incentive Fund STEM Grant in Houston ISD. HISD: Research and Accountability. [ERIC Number ED603678](https://eric.ed.gov/).

Price, L., & Stevens, C. (2017). Teacher Incentive Fund, Cohort 3 — Looking Back, Around, and Ahead: HISD’s Viewfinder for Teacher And Leader Effectiveness. HISD: Research and Accountability.

Price, L., Jordan, S., & Stevens, C. (2016, January). Preferences and Perspectives on Teacher Compensation, 2014-2015. HISD: Internal Publication.

Price, L. (2014). *Parents and Teachers in Title I Schools: A Critical Race Theory Analysis of Parent Engagement* [Unpublished master's thesis]. Peabody College of Education and Human Development, Vanderbilt University. 

<!-- # Skills & Competencies -->

<!-- *Ad Hoc* Analysis • *Ad Hoc* Reporting • -->
<!-- Analytical Skills •  -->
<!-- Annual Budgeting • Budgeting • Business Analysis • -->
<!-- Business Insights • Business Process • Children’s Online Privacy Protection Act "COPPA" at 16 CFR § 312 • Client Relations • Community Impact • Compilation •  -->
<!-- Contract Negotiation • Contract Writing • Creative Problem Solving • Creative Strategy • -->
<!-- Data Analytics • Data Governance • Data Integrity • Data Interpretation • Data Management • Data Manipulation • Data Modeling • Data Retention • Data Privacy • Data Science • Data Strategies • Data Systems • Database Administration • Database Systems • Databases •  -->
<!-- Donor Relations • -->
<!-- Econometrics • Education Department General Administrative Regulations "EDGAR" at 2 CFR and 34 CFR • Extract, Transform, Load (ETL) • Family Educational Rights and Privacy Act "FERPA" at 34 CFR § 99 •  -->
<!-- Key Performance Indicators • KPI Reporting • -->
<!-- Large-scale Data Analysis • Leadership • Legal Requirements • Logic Models • Machine Learning • Metadata • Microsoft Excel • Microsoft Office • Policy Analysis • Policy Writing • Presentations • Primary Research • Privacy Regulations • Problem Solving • Program Assessment • Program Evaluation • Project Management • Quality Assurance • R •  RStudio/Posit • Relational Databases • Reporting Requirements • Spreadsheets • Stata • Statistical Analysis • Statistics • Statutes • Team Management •  -->
<!-- Texas Education Code "TEC" • Tenacious Work Ethic • Texas Government Code "TGC" • Vendor Relations • -->
<!-- Written Communication -->
