---
title: CV
format:
  quarto-cv-pdf: default
author: Lauren E. Price, M.P.P., R.T.S.B.A.
date: last-modified
phone: +1-772-485-2635
address: "Gallup StrengthsFinder: Input • Learner • Ideation • Strategic • Intellection"
email: Lauren.3.Price@gmail.com
fontsize: 11pt
#fontfamily: ebgaramond-maths # default font LaTeX package https://tug.org/FontCatalogue/about.html
#mainfont: Ubuntu # if you want to use a different locally installed font
github: pricele2 # github account
#twitter: twitter # twitter handle
web: linkedin.com 
fontawesome: yes
nocite: '@*'
# bibliography: 
#   peer: peer_bib.bib
#   other: other_bib.bib
validate-yaml: false
csl: apa-cv.csl
---

# Summary

Lorem ipsum sit dolor amet 

# Experience 
\hrule

## **Houston Independent School District \hfill 2014 - 2025**
*Director, Finance Project Management* \hfill Jan. - Sep. 2025

- 1 Lorem ipsum sit dolor amet 

- 2 Lorem ipsum sit dolor amet 

- 3 Lorem ipsum sit dolor amet 

*Senior Analyst then Deputy Director (CTM), Data Science & Analytics* \hfill Oct. 2021 - Dec. 2024

- 1 Lorem ipsum sit dolor amet 

- 2 Lorem ipsum sit dolor amet 

- 3 Lorem ipsum sit dolor amet 

- 4 Lorem ipsum sit dolor amet 

*Program Analyst & Grant Manager, Special Revenue* \hfill Aug. 2014 - Sep. 2021

- 1 Lorem ipsum sit dolor amet 

- 2 Lorem ipsum sit dolor amet 

- 3 Lorem ipsum sit dolor amet 

## **Tennessee (2012-2014) and Colorado (2005-2011) \hfill 2005-2014**

Summer Associate for Research and Policy, *Metro Nashville Public Schools* \hfill 2014

Nashville Promise Neighborhood Practicum Intern, *Martha O'Bryan Center* \hfill 2013-2014

Graduate Research Assistant & Summer Evaluation Associate, *Vanderbilt University* \hfill 2012-2014

Development Director, *Boys Hope Girls Hope of Colorado* \hfill 2010-2011

Program Associate & Project Coordinator, *Community Resource Center*  \hfill 2008-2010

Project Coordinator, Feasibility Studies \& Capital Campaigns, *Robert B. Sharp Company* \hfill 2007-2008

Program Coordinator & Associate Grants Officer, *El Pomar Foundation* \hfill 2005-2007

# Leadership & Impact 
\hrule

*Lorem* 

*Ipsum* 

# Education & Credentials
\hrule

*DAMA International:* [Certified Data Management Professional (CDMP)](https://dama.org/certification/about-cdmp-certification/) \hfill In Progress

*University of Washington:*
[NCES Fellowship](https://www.amplifylearn.ai/isea/) in Innovation Science for Education Analytics  \hfill 2025

*TX Assoc. of School Business Officials:* Registered Texas School Business Administrator (R.T.S.B.A.) \hfill 2020

<!-- - Coursework specializations in Payroll (PAY) and Accounting & Finance (ACT) -->

*Vanderbilt University:* Master's of Public Policy in K-12 Education Policy & Leadership \hfill 3.92 GPA

<!-- - *Parents and Teachers in Title I Schools* [Unpublished master's thesis] -->

*University of Notre Dame:* Bachelor of Arts, *cum laude* \hfill 3.78 GPA

<!-- # Technical Proficiencies -->
<!-- \begin{tabular}{ p{4cm}  p{1.5cm}  p{4cm}  p{1.5cm}  } -->
<!-- R                   & 5 of 5  & Git, GitHub & 4 of 5 \\ -->
<!-- Excel, PowerQuery   & 5 of 5  & Stata       & 4 of 5 \\ -->
<!-- PowerSchool SIS     & 5 of 5  & Rmd, Quarto, LaTeX  & 3 of 5 \\ -->
<!-- SharePoint Admin    & 5 of 5  & PowerBI, Tableau & 3 of 5  \\ -->
<!-- Qualtrics PowerUser & 4 of 5  & Python      & 2 of 5 \\ -->
<!-- PeopleSoft, SAP ERP & 4 of 5 & SQL      & 2 of 5 \\ -->
<!-- \end{tabular} -->

<!-- # Invitations & Awards -->

<!-- Nov 2025. *IS594 Change Catalyst*, [Guest Speaker](https://www.linkedin.com/posts/david-s-charles_changeleadership-organizationalchange-leadershipdevelopment-activity-7405005527484727296-dAmS) \hfill Univ. of Illinois School of Information Sciences -->

<!-- Oct 2024. *EDAD 688 Education Policy Series*, Guest Speaker \hfill Texas A&M College of Education -->

<!-- Apr 2023. *IS595 Competitive Intelligence & Knowledge Management*, Guest Speaker \hfill Univ. of Illinois -->

<!-- Jul 2022. *Diversity Scholarship*, Conference and Workshop \hfill [posit::conf](https://posit.co/conference/faq/), formerly RStudio -->

<!-- Oct 2021. *Featured Publication*, Teacher Incentive Fund (TIF) Evaluations \hfill [ArnieDocs](https://www.arniedocs.info/) -->

<!-- Oct 2021. "Making Performance Pay Pay Off," Conference Presentation \hfill Council of Great City Schools -->

<!-- Nov 2018. *SOCI 437/537 Sociology of Education*, Guest Speaker \hfill Rice University -->

<!-- May 2015. "Parents, Teachers, and Title I," Conference Presentation \hfill [CRSEA](https://crsea.org/crt-101/) 9th Annual Conference -->

<!-- # Selected Publications -->

<!-- Pane, J., Doss, C., Todd, I., & Seaman, D. (2025). Efficacy of Zearn Math over two years in grades 3 to 5: An experiment in Texas. (EdWorkingPaper: 25-1211). Retrieved from Annenberg Institute at Brown University: [https://doi.org/10.26300/e3bq-7g59](https://doi.org/10.26300/e3bq-7g59) -->

<!-- Price, L., & Islam, F. (2025, February). [Technical Documentation](https://www.linkedin.com/in/lauren-e-price-mpp/overlay/1741980965844/single-media-viewer?type=DOCUMENT&profileId=ACoAAADz6gABmAId2NX7YwelXulJgIDVVKZ5mts&lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base%3BGrQgHVtmTRmsyGnRySj2Dg%3D%3D): Local Norms & GT Matrix Scores for Students Entering Kindergarten in SY25-26. HISD: Data Science & Analytics. -->

<!-- Price, L., & Cortez, J. (2024, September 30). Technical Documentation for Efficacy of Zearn Math, IES Award [R305A230170](https://ies.ed.gov/funding/grantsearch/details.asp?ID=5835). HISD: Data Science & Analytics. -->

<!-- Price, L., Lasode, M., & Powers, K. (2023, December 13). Memorandum To Chief Financial Officer: FY25 Forecasting Models for Student Average Daily Attendance. HISD: Internal Memo. -->

<!-- Lasode, M., Price, L., Abdoli, M., & Hovey, I. (2022, July 7). [2021-2022 Campus Demographic Report](https://tx01001591.schoolwires.net/site/handlers/filedownload.ashx?moduleinstanceid=392028&dataid=424429&FileName=Campus%20Demographic%20Report%202021-2022.pdf). HISD: Research and Accountability. -->

<!-- Price, L., & Scuello, M. (2022, May). Evidence of Promise from the Magnet Schools Assistance Program: Recruiting Students to HISD’s Secondary STEM Magnet Schools. HISD: Internal Publication. -->

<!-- Price, L., & Matney, A. (2021, December 14). Memorandum to Executive Officer, Student Support: Additional Students Identified as Eligible Under McKinney-Vento. HISD: Internal Memo. -->

<!-- Aulicino, C., Rinehart, C., & Price, L. (2021, October). Secondary STEM Magnet Programs Study: Year 2. Metis Associates: Internal Publication for HISD. -->

<!-- Aulicino, C., Rinehart, C., & Price, Lauren. (2020, September). STEM Magnet Program Study: Year 1. Metis Associates: Internal Publication for HISD. -->

<!-- Price, L., Christian, M., & Stevens, C. (2018a). A Matched-Comparison Analysis of Math and Science STAAR Scores: Teacher Incentive Fund STEM Grant in Houston ISD. HISD: Research And Accountability. [ERIC Number ED603680](https://eric.ed.gov/). -->

<!-- Price, L., Cramer, E., Milanowski, A., Mader, J., Robertson, D., & Stevens, C. (2018b). A Human Capital Approach to Improving STEM Education: Teacher Incentive Fund STEM Grant in Houston ISD. HISD: Research and Accountability. [ERIC Number ED603681](https://eric.ed.gov/). -->

<!-- Price, L., Provencher, S., & Stevens, C. (2018c). A Descriptive Overview: Teacher Incentive Fund STEM Grant in Houston ISD. HISD: Research and Accountability. [ERIC Number ED603678](https://eric.ed.gov/). -->

<!-- Price, L., & Stevens, C. (2017). Teacher Incentive Fund, Cohort 3 — Looking Back, Around, and Ahead: HISD’s Viewfinder for Teacher And Leader Effectiveness. HISD: Research and Accountability. -->

<!-- Price, L., Jordan, S., & Stevens, C. (2016, January). Preferences and Perspectives on Teacher Compensation, 2014-2015. HISD: Internal Publication. -->

<!-- Price, L. (2014). *Parents and Teachers in Title I Schools: A Critical Race Theory Analysis of Parent Engagement* [Unpublished master's thesis]. Peabody College of Education and Human Development, Vanderbilt University.  -->

<!-- # Skills & Competencies -->

<!-- *Ad Hoc* Analysis • *Ad Hoc* Reporting • -->
<!-- Analytical Skills • -->
<!-- Annual Budgeting • Budgeting • Business Analysis • -->
<!-- Business Insights • Business Process • Children’s Online Privacy Protection Act "COPPA" at 16 CFR § 312 • Client Relations • Community Impact • Compilation • -->
<!-- Contract Negotiation • Contract Writing • Creative Problem Solving • Creative Strategy • -->
<!-- Data Analytics • Data Governance • Data Integrity • Data Interpretation • Data Management • Data Manipulation • Data Modeling • Data Retention • Data Privacy • Data Science • Data Strategies • Data Systems • Database Administration • Database Systems • Databases • -->
<!-- Donor Relations • -->
<!-- Econometrics • Education Department General Administrative Regulations "EDGAR" at 2 CFR and 34 CFR • Extract, Transform, Load (ETL) • Family Educational Rights and Privacy Act "FERPA" at 34 CFR § 99 • -->
<!-- Key Performance Indicators • KPI Reporting • -->
<!-- Large-scale Data Analysis • Leadership • Legal Requirements • Logic Models • Machine Learning • Metadata • Microsoft Excel • Microsoft Office • Policy Analysis • Policy Writing • Presentations • Primary Research • Privacy Regulations • Problem Solving • Program Assessment • Program Evaluation • Project Management • Quality Assurance • R •  RStudio/Posit • Relational Databases • Reporting Requirements • Spreadsheets • Stata • Statistical Analysis • Statistics • Statutes • Team Management • -->
<!-- Texas Education Code "TEC" • Tenacious Work Ethic • Texas Government Code "TGC" • Vendor Relations • -->
<!-- Written Communication -->
